(function(){var ua=navigator.userAgent.toLowerCase();var appv=navigator.appVersion;var html=document.documentElement;var isIos=/ip(hone|od|ad)/i.test(ua);var device={iphone:"iphone",ipod:"ipod",ipad:"ipad",samsung:"samsung|sm-",huawei:"huawei",meizu:"mx[0-9]+"};var uaContextReg=/context\:([^\s]+)/i;var tryToGetContext=uaContextReg.exec(ua);var vArr,ver;var dev;if(isIos){html.classList.add("fl-ios");vArr=appv.match(/OS (\d+)[_\.](?:\d+)[_\.]?(?:\d+)?/);ver=parseInt(vArr[1],10);if(ver>=8){html.classList.add("fl-hairlines");}}else{vArr=appv;ver=parseInt(ua.substr(ua.indexOf('android')+8,3));html.classList.add("fl-android");if(ver<6){html.classList.add("fl-android-"+ver);}}
for(dev in device){if(device.hasOwnProperty(dev)){if((new RegExp("\\b"+device[dev]+"\\b")).test(ua)){html.classList.add("fl-"+dev);break;}}}
if(tryToGetContext&&tryToGetContext[1]=='com'){document.querySelector('meta[name=viewport]').setAttribute('content','initial-scale=1.0,user-scalable=no,minimum-scale=1.0,maximum-scale=1.0');}}());(function(){!/f\.(51)?fanli\.com/.test(document.domain)&&document.addEventListener("DOMContentLoaded",function(ev){var ua=navigator.userAgent.toLowerCase();var isFanli=ua.indexOf('fanli')>-1;if(isFanli){var iframe=document.createElement("iframe");var iframeStyle=document.createAttribute("style");var iframeSrc=document.createAttribute("src")
iframeStyle.nodeValue="display:none;width:0;height:0;";iframeSrc.nodeValue="ifanli://m.51fanli.com/app/event/readystatechange?state=complete";iframe.setAttributeNode(iframeStyle);iframe.setAttributeNode(iframeSrc);document.body.appendChild(iframe);setTimeout(function(){document.body.removeChild(iframe);},250);}},false);}());(function(win,doc){var script=doc.querySelector("#J_script_attrsniffer");var remwidth;var remSwitch;var remmaxwidth;var evt='onorientationchange'in win?'orientationchange':'resize';var timer=null;var ua=navigator.userAgent.toLowerCase();var isIos=/ip(hone|od|ad)/i.test(ua);var isFanli=ua.indexOf('fanli')>-1;var isIpad=/ipad/i.test(ua);if(!script){return;}
remwidth=script.getAttribute("data-remwidth");remSwitch=script.getAttribute("data-remswitch");remmaxwidth=script.getAttribute("data-remmaxwidth");if(remSwitch=="[remswitch]"){return;}
remwidth=(remwidth=="[remwidth]"?750:Number(remwidth));function setFontSize(){var docEl=doc.documentElement;var winWidth=window.screen.width;var originFontSize;var definedFontSize=(winWidth/remwidth)*100;if(remmaxwidth&&remmaxwidth!=="[remmaxwidth]"&&definedFontSize>Number(remmaxwidth)){definedFontSize=Number(remmaxwidth);}
docEl.setAttribute('data-screenwidth',winWidth);docEl.style.fontSize=definedFontSize+'px';originFontSize=parseFloat(window.getComputedStyle(docEl,null).getPropertyValue("font-size"));if(!isIos&&definedFontSize!=originFontSize){originFontSize=(originFontSize%1===0)?(originFontSize+0.5):originFontSize;docEl.style.fontSize=(definedFontSize/originFontSize)*definedFontSize+'px';}}
win.addEventListener(evt,function(){clearTimeout(timer);timer=setTimeout(setFontSize,300);},false);win.addEventListener("pageshow",function(e){if(e.persisted){clearTimeout(timer);timer=setTimeout(setFontSize,300);}},false);setFontSize();}(window,document));(function(){localStorage.clear=function(){};localStorage.removeItem('LS_JQUERY_LOCAL');localStorage.removeItem('LS_VUE_LOCAL');window.LSLibsCache=(function(){var supportLibs={jquery:{src:'//static2.51fanli.net/common/libs/fmu/js/vendors/jquery/jquery.min.js',version:'v2.1.1',hash:'a0a7b44651',keyprefix:'__LS_JQUERY',keyname:'JQUERY_LS_KEY'},vue:{src:'//static2.51fanli.net/common/libs/fmu/js/vendors/vue/vue.min.js',version:'v2.4.0',hash:'aaf9c760ef',keyprefix:'__LS_VUE',keyname:'VUE_LS_KEY'},zepto:{src:'//static2.51fanli.net/common/libs/gmu/zepto.min.js',version:'v1.0.1',hash:'186b18d8bc',keyprefix:'__LS_ZEPTO',keyname:'ZEPTO_LS_KEY'}};function _load(needlist,isstore){for(var i=0,len=needlist.length;i<len;i++){var vendor=supportLibs[needlist[i]];if(!vendor){continue;}
if(!isstore){loadScript(vendor);}else{prepareFile(vendor);}}}
function prepareFile(vendor){var k1=localStorage.getItem(vendor.keyname);var k2=vendor.keyprefix+'_'+vendor.version;if(k1!=k2){localStorage.removeItem(k1);localStorage.removeItem(k2);loadScript(vendor);loadFile(vendor);}else{var content=localStorage.getItem(k2);if(content){window.eval(content);}else{loadScript(vendor);loadFile(vendor);}}}
function loadScript(vendor){wagv.pageJsListArr.push(vendor.src+'?'+vendor.hash);}
function loadFile(vendor){var k=vendor.keyprefix+'_'+vendor.version;var xhr=new XMLHttpRequest();xhr.open("GET",vendor.src+'?'+vendor.hash);xhr.send(null);xhr.onreadystatechange=function(){if(xhr.readyState==4&&xhr.status==200){localStorage.setItem(vendor.keyname,k);localStorage.setItem(k,xhr.responseText);}}}
function _addLib(vendor){loadFile(vendor);}
return{load:_load,addLib:_addLib}})();}());